config/routes.rb
Pos::Application.routes.draw do
 
  namespace :admin do
    resources :categories
    resources :products
  end

  resources :categories
  resources :line_items
  resources :products

  resources :orders do
    member do
      get 'remove_item'
      get 'receipt'
      get 'thanks'
    end
    collection do
      get 'current'
      put 'current'
    end
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates_presence_of :name
  validates :name, :uniqueness => { :case_sensitive => false }

  attr_accessible :image, :name

end

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"
  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @admin_categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.json
  def new
    @admin_category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @admin_category = Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @admin_category = Category.new(params[:category])

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @admin_category, status: :created, location: @admin_category }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.json
  def update
    @admin_category = Category.find(params[:id])

    respond_to do |format|
      if @admin_category.update_attributes(params[:category])
        format.html { redirect_to admin_category_path(@admin_category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @admin_category = Category.find(params[:id])
    @admin_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    categories = Category.all
    render json: categories
  end

  def show
    category = Category.find(params[:id])
    render json: category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @admin_category]) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: "radius"%>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="row">
	<h1 class="center">Edit Category</h1>
	<div class="small-2 large-6 columns">

<%= form_for([:admin, @admin_category]) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: "radius"%> <%= link_to 'Delete', admin_category_path(@admin_category), class: "round right button alert", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>

		<%= link_to 'Back', admin_categories_path, class: "bold"  %>
	</div>
</div>
<br />

app/views/admin/categories/index.html.erb
<div class="row">
  <h1 class="center">Admin Category Section</h1>
    <div class="small-2 large-6columns, spaced">
      <table class="categorytablewidth">
        <tr>
          <th class="left title">Name</th>
        </tr>

      <% @admin_categories.each do |admin_category| %>
        <tr>
          <td><%= admin_category.name%></td>
          <td class="cellwidth bold"><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
          <td class="cellwidth bold"><%= link_to 'Delete', admin_category_path(admin_category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </table>
      <br />
      <%= link_to 'New Category', new_admin_category_path, class: "button radius" %>
    </div>
  </div>

<br />

app/views/admin/categories/new.html.erb
<div class="row">
	<h1 class="center">New Category</h1>
	<div class="small-2 large-6 columns">

		<%= render 'form' %>
		<%= link_to 'Back', admin_categories_path, class: "bold"  %>
	<br />
	<br />
	</div>
</div>

app/views/admin/categories/show.html.erb
<div class="row">
 <h1 class="center">New Category</h1>
  <div class="small-2 large-6 columns">   
    <p id="notice"><%= notice %></p>
    <div> 
      <p><span class="bold">Name:</span>  <%= @admin_category.name %></p>
    </div>
<br />
<%= link_to 'Edit', edit_admin_category_path(@admin_category), class: "bold" %> |
<%= link_to 'Back', admin_categories_path, class: "bold" %>
</br>

<br />