config/routes.rb
Pos::Application.routes.draw do
 
  namespace :admin do
    resources :categories
    resources :products
  end

  resources :categories
  resources :line_items
  resources :products

  resources :orders do
    member do
      get 'remove_item'
      get 'receipt'
      get 'thanks'
    end
    collection do
      get 'current'
      put 'current'
    end
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items

  validates_presence_of :category_id, :name, :price_cents
  
  
  attr_accessor :price

  attr_accessible :category_id, :description, :image, :name, :price_cents, :upc_code, :price

  def price
    price_cents/100.0 if price_cents
  end

  def price= price
  	self.price_cents = (price.to_f*100).round
  end

end

# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  price_cents :integer
#  upc_code    :string(255)
#  image       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.json
  def new
    @admin_product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Product.new(params[:product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_path(@admin_product), notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:product])
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    products = Product.all
    render json: products
  end

  def show
    products = Product.find(params[:id])
    render json: products
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin,@admin_product]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :upc_code, label: 'UPC Code' %>
    <%= f.input :price %>
    <%= f.input :category_id, collection: Category.all %>
  </div>
<br />
  <div class="form-actions">
    <%= f.button :submit, class: "radius" %>
    
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
	<h1 class="center">Edit Product</h1>
	<div class="small-2 large-6 columns">
		<%#= render 'form' %>

			<%= simple_form_for([:admin,@admin_product]) do |f| %>
			  <%= f.error_notification %>

			  <div class="form-inputs">
			    <%= f.input :name %>
			    <%= f.input :description %>
			    <%= f.input :upc_code, label: 'UPC Code' %>
			    <%= f.input :price %>
			    <%= f.input :category_id, collection: Category.all %>
			  </div>
			<br />
			  <div class="form-actions">
			    <%= f.button :submit, class: "radius" %> <%= link_to 'Delete', admin_product_path(@admin_product), class: "round right button alert", method: :delete, data: { confirm: 'Are you sure?' } %>
			  </div>
			<% end %>
		<%= link_to 'Back', admin_products_path, class: "bold"  %>
	</div>
</div>
<br />

app/views/admin/products/index.html.erb
<div class="row">
  <h1 class="center">Admin Product Section</h1>
    <div class="small-2 large-8columns, spaced">

        <table class="producttablewidth">
          <tr class="title">
            <th>Name</th>
            <th>Description</th>
            <th>UPC code</th>
            <th>Price</th>
            <th>Category</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>

        <% @admin_products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.upc_code %></td>
            <td><%= number_to_currency(product.price_cents/100.0) if product.price_cents %></td>
            <td><%= product.category.name if product.category %></td>
            <td class="bold"><%= link_to 'Edit', edit_admin_product_path(product) %></td>
            <td class="bold"><%= link_to 'Delete', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </table>

        <br />

        <%= link_to 'New Product', new_admin_product_path, class: "button radius " %>
    </div>
</div>

<br />

app/views/admin/products/new.html.erb
<div class="row">
	<h1 class="center">New Product</h1>
	<div class="small-2 large-6 columns">

		<%= render 'form' %>
		<%= link_to 'Back', admin_products_path %>
	<br />
	<br />
	</div>
</div>

app/views/admin/products/show.html.erb
<div class="row">
 <h1 class="center">New Product</h1>
  <div class="small-2 large-4 columns">   
    <p id="notice"><%= notice %></p>
    <div> 
      <p><span class="bold">Name:</span><span class="right"><%= @admin_product.name %></span></p>
      <p><span class="bold">Description:</span><span class="right"><%= @admin_product.description %></span></p>
      <p><span class="bold">UPC Code:</span><span class="right"><%= @admin_product.upc_code %></span></p>
      <p><span class="bold">Price:</span><span class="right"><%= @admin_product.price %></span></p>
      <p><span class="bold">Category:</span><span class="right"><%= @admin_product.category.name %></span></p>
    </div>
<br />
<%= link_to 'Edit', edit_admin_product_path(@admin_product), class: "bold" %> |
<%= link_to 'Back', admin_products_path, class: "bold" %>
</br>

<br />